### ISSUE TITLE
Undefined method error with Rails 5.1.0

### ISSUE THREAD

**Issue by zarembas** [wrr/rack-wwwhisper#4]
This is the error I'm getting when trying to start the Rails server: `~/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.0/lib/action_dispatch/middleware/stack.rb:35:in `build': undefined method `new' for "Rack::WWWhisper":String (NoMethodError)`

**Comment by vassyz** [comment]
The quotes were the issue:

```ruby
config.middleware.insert 0, "Rack::WWWhisper"
```

should be:

```ruby
config.middleware.insert 0, Rack::WWWhisper
```
